name: zlmPushRA

on: workflow_dispatch
      
jobs:
  RUN:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push Image
      run: |
        echo "dckr_pat_E_7AM4AtE3IIZbzRUbty0quwmgc" | docker login -u "drzawlinmg" --password-stdin
        docker image build -t drzawlinmg/stable:mltbra .
        docker push drzawlinmg/stable:mltbra
